"""Table_Warehouse_deleted_product-id

Revision ID: 1708434055
Revises: 
Create Date: 2024-02-20 13:00:55.702985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1708434055'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(precision=127), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehoue',
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_price', sa.Float(), nullable=False),
    sa.Column('product_quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehoue')
    op.drop_table('balance')
    # ### end Alembic commands ###
