"""Upgrade_DB_from_txt_on_index___

Revision ID: 1708368006
Revises: 1708367925
Create Date: 2024-02-19 18:40:06.440291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1708368006'
down_revision: Union[str, None] = '1708367925'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_balance_id'), 'balance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balance_id'), table_name='balance')
    # ### end Alembic commands ###
